# Generated by Django 4.2.6 on 2023-10-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=30)),
                ('book_author', models.CharField(max_length=20)),
                ('book_genre', models.CharField(choices=[('FIC', 'Fiction'), ('FANT', 'Fantasy'), ('NON-FIC', 'Non-fiction')], max_length=15)),
            ],
        ),
    ]
